// <auto-generated />
using System;
using DataAccessLibary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLibary.Migrations
{
    [DbContext(typeof(BdContext))]
    [Migration("20230225112842_InitialBD")]
    partial class InitialBD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLibary.Order", b =>
                {
                    b.Property<int>("IDzamówienia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDzamówienia"));

                    b.Property<string>("AdresOdbiorcy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataWymagania")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataWysylki")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZamówienia")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fracht")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("IDklienta")
                        .HasColumnType("int");

                    b.Property<int>("IDpracownika")
                        .HasColumnType("int");

                    b.Property<int>("IDspedytora")
                        .HasColumnType("int");

                    b.Property<string>("KodPocztowy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KrajOdbiorcy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiastoOdbiorcy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaOdbiorcy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionOdbiorcy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDzamówienia");

                    b.ToTable("Order");
                });
#pragma warning restore 612, 618
        }
    }
}
