// <auto-generated />
using System;
using DataAccessLibary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLibary.Migrations
{
    [DbContext(typeof(BdContext))]
    partial class BdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLibary.Order", b =>
                {
                    b.Property<int>("IDzamówienia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDzamówienia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDzamówienia"));

                    b.Property<string>("AdresOdbiorcy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AdresOdbiorcy");

                    b.Property<DateTime>("DataWymagania")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataWymagana");

                    b.Property<DateTime>("DataWysylki")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataWysyłki");

                    b.Property<DateTime>("DataZamówienia")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataZamówienia");

                    b.Property<decimal>("Fracht")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("Fracht");

                    b.Property<int>("IDklienta")
                        .HasColumnType("int")
                        .HasColumnName("NazwaKolumnyWTwojejBazieDanych2");

                    b.Property<int>("IDpracownika")
                        .HasColumnType("int")
                        .HasColumnName("IDpracownika");

                    b.Property<int>("IDspedytora")
                        .HasColumnType("int")
                        .HasColumnName("IDspedytora");

                    b.Property<string>("KodPocztowy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KodPocztowyOdbiorcy");

                    b.Property<string>("KrajOdbiorcy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KrajOdbiorcy");

                    b.Property<string>("MiastoOdbiorcy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MiastoOdbiorcy");

                    b.Property<string>("NazwaOdbiorcy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NazwaOdbiorcy");

                    b.Property<string>("RegionOdbiorcy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RegionOdbiorcy");

                    b.HasKey("IDzamówienia");

                    b.ToTable("Zamówienia", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
